---
- name: copy files and directories 
  hosts: myservers
  tasks:

   - name: copy files
     copy:
       src: /etc/hosts
       dest: /root/
       owner: root
       group: armaan
       mode: 0755

   - name: copy dirs
     copy:
       src: /root/apps
       dest: /root/
       owner: root
       group: root
       mode: 0700
