---
- name:
  hosts: myservers
  tasks:
    - name: enabling port for nginx
      firewalld:
        port: 80/tcp
        permanent: true
        state: enabled

    - name: reload the firewalld 
      service:
        name: firewalld
        state: reloaded
